# Lab Platform Device Agent Configuration - Dual Module Example
# This example shows how to configure a device with both NDI and projector modules

device_id: "lab-device-dual-01"
labels: ["ndi", "projector", "multi-module"]

# MQTT broker connection
mqtt:
  host: "localhost"
  port: 1883
  username: "mqtt"
  password: "public"

# Heartbeat interval in seconds
heartbeat_interval_s: 10

# Modules configuration
# Both NDI and projector modules will be loaded dynamically
modules:
  # NDI module configuration
  ndi:
    # Path to NDI runtime libraries (adjust for your system)
    ndi_path: "/usr/local/lib/ndi"
    # Command template to start NDI viewer
    start_cmd_template: "ndi-viewer {source}"
    # Command template to start NDI recording
    record_start_cmd_template: "ndi-recorder -i {source} -o /tmp/recording_{device_id}.mp4"
    # Log file for NDI module
    log_file: "/tmp/ndi_{device_id}.log"
    # Whether to restart viewer when changing input
    set_input_restart: true
    # Optional: Additional NDI environment variables
    ndi_env:
      NDI_RECV_COLOR_FORMAT: "UYVY"
      NDI_RECV_BANDWIDTH: "highest"
  
  # Projector module configuration
  projector:
    # Serial port for projector communication (will auto-discover if not specified)
    # serial_port: "/dev/ttyUSB0"  # Uncomment and adjust if needed
    # Serial communication settings
    baudrate: 9600
    timeout: 1.0
    # Automatically discover USB serial port
    auto_discover_port: true
    # Log file for projector module
    log_file: "/tmp/projector_{device_id}.log"
